project:
  type: book
  output-dir: docs

book:
  title: "Uncovering the Causes: From Correlation to Causation"
  subtitle: "A Basic Introduction to Applied Causal Inference"
  author: "Kevin Li (London School of Economics)"
  cover-image: cover.jpeg
  search: true
  chapters:
    - index.qmd
    - correlation.qmd
    - frameworks.qmd
    - part: "Related Statistical Topics"
  appendices:
    - mechanics.qmd
    - identification.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-depth: 1
    css: styles.css
    toc: true
    toc-depth: 2
    grid:
      sidebar-width: 300px
      body-width: 700px
      margin-width: 350px
      gutter-width: 1em
    html-math-method: mathjax
    crossref:
      eq-prefix: eq.
      def-prefix: definition
      thm-prefix: theorem
    include-in-header:
      text: |
        <script src="mathjax-config.js"></script>
  pdf:
    documentclass: scrreprt

editor: visual

