# Correlation vs. Causation

::: {.callout-tip appearance="simple"}
## Overview

In this chapter, we discuss why correlation is not causation:

1.  Discuss the concept of **correlation**.
2.  Discuss how **confounders** and **selection bias** mean correlation is not equal to causation.
3.  Briefly discuss broad ideas of how we can address the issues of confounders and selection bias to go from correlation to causation.
:::

<br />

## What is Correlation?

::: {.callout-important appearance="simple"}
## Key Definition: **Correlation**

Correlation is how one variable changes when the other variable changes.
:::

For example, let us say that our treatment is whether or not you went to college. Our outcome of interest is you career earnings. To calculate a correlation measure, we find the average career earnings of someone who didn't go to college, and the average career earnings of someone who did go to college.

Once we have these averages, we can compare them to determine what correlation we have:

| Type of Correlation                                                            | How to Identify                                                         |
|--------------------------------------|----------------------------------|
| **Positive Correlation** between going to college and average career earnings. | If by going to college, you get **higher** average career earnings.     |
| **Negative Correlation** between going to college and average career earnings. | If by going to college, you get **lower** average career earnings.      |
| **No Correlation** between going to college and average career earnings.       | If by going to college **does not change** the average career earnings. |

: {tbl-colwidths="\[50,50\]" .bordered}

We can generalise this to find the correlation of any treatment and outcome:

$$
\text{correlation} = Y_t - Y_c
$$

Where $Y_t$ is the average outcome value of individuals who do receive the treatment, and $Y_c$ is the average outcome of individuals who do not receive the treatment.

<br />

## Correlation is not Causation

You probably have heard the phrase: "*correlation is not causation*". But what does this mean? Imagine this causal scenario as an example:

| Our Causal Question: $D \rightarrow Y$                                  | Treatment $D$                     | Outcome $Y$                    |
|-----------------------------------|------------------|------------------|
| How does going to the hospital to receive treatment affect your health? | Going to the hospital (yes or no) | Some measure of health outcome |

: {tbl-colwidths="\[50,25,25\]" .bordered}

If we just collect correlation data, we likely find the following:

-   The average health outcome of individuals who went to the hospital is [quite low]{.underline}.
-   The average health outcome of individuals who did not go to the hospital is [quite high]{.underline}.
-   Thus, we find that going to the hospital is correlated with **worse** health outcomes.

Does this mean that going to the hospital **causes** worse health? The answer is **no**! Our correlation is incorrectly measuring the causal effect because of a **confounder**.

::: {.callout-important appearance="simple"}
## Key Definition: **Confounders**

A confounder is a third variable that has the following characteristics:

1.  The confounder is correlated (positive or negative) with the outcome variable.
2.  The confounder causes who gets and doesn't get the treatment.
3.  The confounder is **not** itself caused by the treatment.
:::

In this example, a confounder could be **smoking**.

-   Smoking will worsen health outcomes. Someone who smokes is also more likely to visit the hospital with health complications (getting the treatment)
-   That means people who go to the hospital (get the treatment) start out with (on average) worse health outcomes than people who did not go to the hospital.

This means that the hospital might actually be boosting people's health outcomes significantly. But since the people going to the hospital start out with such bad health, even the positive effects of the hospital cannot get their average health outcome to be equal to the people who did not go to the hospital.

Thus, while our correlation says that going to the hospital worsens our health outcomes, the actual causal effect is that going to the hospital boosts our health outcomes.

<br />

## Formalising Selection Bias

Let us generalise why correlation is not equal to causation. We split every individual in our study into two groups - those who received the treatment, and those who haven't. Using what we learned in the [last chapter](frameworks.qmd), we get:

| Group                                 | Observed Outcome                   | Counterfactual            | **Real Treatment Effect**                                       |
|----------------|----------------|----------------|-------------------------|
| Group that got the treatment          | $Y_t = \textcolor{purple}{Y_t(1)}$ | $\textcolor{red}{Y_t(0)}$ | $\tau_t = \textcolor{purple}{Y_t(1)} - \textcolor{red}{Y_t(0)}$ |
| Group that did not get the treatment. | $Y_c = \textcolor{purple}{Y_c(0)}$ | $\textcolor{red}{Y_t(1)}$ | $\tau_c = \textcolor{red}{Y_c(1)} - \textcolor{purple}{Y_c(0)}$ |

: {tbl-colwidths="\[25,25,20,30\]" .bordered}

We know the real treatment effects $\tau_t$ and $\tau_c$. But how do these treatment effects compare to correlation? Recall our definition of correlation:

$$
\text{correlation} = Y_t - Y_c \ = \ \textcolor{purple}{Y_t(1)} - \textcolor{purple}{Y_c(0)}
$$

Notice how this equation for correlation is **not the same** to either causal effect we found above. However, if $\textcolor{purple}{Y_c(0)}$ and $\textcolor{red}{Y_t(0)}$ are equal, then our correlation would indeed be the same as the causal effect of the treatment group, $\tau_t$. So are these equal?

-   $\textcolor{purple}{Y_c(0)}$ is the potential outcome of group $c$ in the parallel world they do not get the treatment (which we observe)
-   $\textcolor{red}{Y_t(0)}$ is the potential outcome of group $t$ in the parallel world they do not get the treament (which is counterfactual).
-   Thus, both are the outcome value of all individuals, had they not received the treatment.

So are these two equal? Not if there is a **confounder**.

-   Since the confounder is correlated with the outcome, that means people with different values of the confounder will have different outcomes had they not received the treatment.
-   And since the confounder affects who gets and does not get the treatment, it might result in the treatment and control groups having different no-treatment potential outcomes.

Thus, if there is a confounder, then $\textcolor{purple}{Y_c(0)}$ and $\textcolor{red}{Y_t(0)}$ are not equal, and correlation does not equal causation. This error caused by confounders is called **selection bias** (or endogeneity bias).

<br />

## Dealing with Confounders

We have discussed how the presence of confounders can result in our correlation being completely different from the causal effect.

To get the correct causal effect of a treatment on an outcome, we must find some way to "account" for confounder. But first, how do we identify confounders?

-   Unfortunately, there is not some magical statistical test to find confounders.
-   Instead, we have to use our own *knowledge* and *intuition* about a topic to think of potential confounders.
-   Typically, researchers identify potential confounders by reading a lot about the topics they are studying, and thinking about how other variables might meet the definition of a confounder.

Once we have identified confounders, there are two main ways we do this in causal inference:

1.  We **control** for confounders. This basically means we account for the influence of confounder $X$, and get rid of that part of influence.
2.  We **determine who gets treated**. For example, if we randomly decide who gets the treatment and who doesn't (such as flipping a coin), that means **we the researchers** are controlling who gets the treatment, and not the confounder. Thus, the confounder no longer determines who gets and doesn't get the treatment, and thus is no longer a confounder.

We will cover a variety of different causal research designs from chapter 3 onwards, which will apply these strategies to isolate causal effects, and go from correlation to causation.
