# Preface {.unnumbered}

How does raising the minimum wage cause unemployment levels to change? How does going to university cause our career earnings to change? How does taking the vaccine cause our chances of getting the disease to change? How do diversity policies cause changes in reported discrimination?

From politics to health, economics to science, causation is key. Our lives revolve around causation - yet so many of us do not understand causation.

We have all heard of the saying - "correlation is not causation". But what does that actually mean? How do we go from an observed correlation to finding the causal effect?

This booklet aims to teach the fundamentals of causal inference, while relying on as little mathematics and complexity as possible. The goal is that with the knowledge in this booklet, you will be able to critically assess the claims of others - is it truly causation or just correlation? You will also be able to conduct your own causal analysis using the R programming language.

<br />

## Prerequisites

I aim to avoid as much mathematics and technical notation as possible. I recommend that before starting, one has an understanding of the following:

1.  Basic statistical concepts, such as mean/average, binary vs. continuous variables.
2.  Basic algebra concepts, such as slope of a linear line.
3.  (Optional but helpful) a basic understanding of statistical inference and simple regression.

I provide R-code to implement the methods I discuss in this booklet. While I provide the code for the methods, I do not teach how to code in R in this booklet. Thus, if you wish to implement these methods, I recommend looking at simple tutorials regarding coding in R.

I also provide some more detailed notes in blue drop-down info boxes, for those who are interested in a more thorough approach.

<br />

## Layout

This booklet is laid out in the following manner:

-   In the first two chapters, we discuss the basics of causal inference: what is causation, how is it different from correlation, and what are the challenges of finding causal effects.
-   For the remaining main chapters, we discuss different methods to estimate causal effects.
-   In the **appendix**, I provide some useful complementary statistical methods that can be used alongside causal inference techniques.
